//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid Id { get; set; }
        public string Text { get; set; }
        public Nullable<System.Guid> AccountRefID { get; set; }
        public System.Guid PictureRefID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Picture Picture { get; set; }
    }
}
